### ISSUE TITLE
Call to undefined function bcg_get_posttype() in \wp-content\plugins\blog-categories-for-groups\core\bcg-functions.php on line 328

### ISSUE THREAD

**Issue by brytey2k** [buddydev/blog-categories-for-groups#12]
I dont get this issue when I am logged in as an admin of a group. But when I log in as a member, I get this error as soon as I click the blog page

**Comment by raviousprime** [comment]
Hello Brytey,
Thank you for reporting this bug. I have updated the plugin. Please clone the latest code.
Thank You
Ravi
